version: "3.8"
services:
  backend:
    build: ./backend
    container_name: url_irl_backend_c
    environment:
      port: 5000
    ports:
      - '5000:5000'
  frontend:
    build: ./frontend
    container_name: url_irl_frontend_c
    environment:
      VITE_SERVER_NAME: "backend"
      VITE_SERVER_PORT: 5000
      VITE_PORT: 8080
    ports:
      - '8080:8080'
    stdin_open: true